### ISSUE TITLE
webpage 404

### ISSUE THREAD

**Issue by Chahua09** [ritikrohan/NFTgenerator#3]
404 page will turn out when generating more than 500 copies at once.

**Comment by ritikrohan** [comment]
Hey, @Chahua09 could you please share more information regarding this, so I can look into it. 
Maybe a video link would help me.
Thanks for pointing out though.

**Comment by Chahua09** [comment]
> Hey, @Chahua09 could you please share more information regarding this, so I can look into it. Maybe a video link would help me. Thanks for pointing out though.

Hello, thank you for your response.

After entering "Files are being processed.." phase, 404 page will turn out within a minute,
when I was trying to generate more than 250 copies at once.
This happens when there are 9 layers of 2000x2000 original images and the output was 1200x1200.

But when I was trying to make output of 600x600 from 5 layers of 600x600 original images, I was able to generate 2000 copies at once without this issue.( still has this issue when trying to generate 10000 copies at once.)

**Comment by ritikrohan** [comment]
Seems like I did put a few checks to limit the resolution cos it might overburden your system. I will fix it in the new upcoming patch soon.
But I would still encourage you to **if possible**  please drop me a video for this so I can understand the issue closely.

Thanks, also if you do think anything could be made better please add your thoughts as well.

**Comment by Chahua09** [comment]
> Seems like I did put a few checks to limit the resolution cos it might overburden your system. I will fix it in the new upcoming patch soon. But I would still encourage you to **if possible** please drop me a video for this so I can understand the issue closely.
> 
> Thanks, also if you do think anything could be made better please add your thoughts as well.

Thank you.
I assume it's like a data volume limit or overflow since when I am working with smaller images I get to generate more copies without issue.
Sorry it is not possible for me to drop a video here.
You can ask if I haven't stated my issue clearly.

Also, I find that there is no attribute value in my metadata files, which is to describe the layers and values of the layers. (all images are generated properly.)
Am I doing sth wrong or it's just your code?
In your Youtube guide video, there was no metadata file generated.

**Comment by ritikrohan** [comment]
Hey sorry for the delay in reply well the metadata is actually a field in the JSON rather than a file which you can use when doing a bulk upload to any NFT platform.

I will try to fix this code after 6 july for sure. I have a very important to finish off by 6 July.

Thanks again!
